### ISSUE TITLE
Roadmap to v3.0.0

### ISSUE THREAD

**Issue by coolaj86** [coolaj86/ajquery.js#8]
v3's biggest focus will be regearing to embracing Ai, without being held back by legacy browser support.

I've also been thinking about how to incorporate ESM and TypeScript without breaking from the browser-first paradigm.

- [x] break backwards compatibility
- [x] make dumb enough for Ai to understand
- [x] add more package bloat, unapologetically

**Comment by coolaj86** [comment]
Done! Published first as v3.0.0, and then v3.0.1!!

See also:
- #9 
- #12
